### ISSUE TITLE
Use ruff instead of pylint and friends

### ISSUE THREAD

**Issue by btschwertfeger** [btschwertfeger/python-kraken-sdk#140]
Ruff is way faster and offers the inclusion of flake8, isort and more. It could replace pylint and decrease the CI time as well as the local pre-commit checking. 

https://beta.ruff.rs/docs/settings/#flake8-errmsg-max-string-length

Some example configuration: 

```toml

[tool.ruff]
# https://beta.ruff.rs/docs/settings/
# src = ["kraken"]

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = [] # Line to long

respect-gitignore = true
exclude = [
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".ruff_cache",
    ".cache",
    "build",
    "dist",
    "venv",
]

line-length = 130
cache-dir = "~/.cache/ruff"

[tool.ruff.per-file-ignores]
"setup.py" = ["F401"] # unused import
"tests/*.py" = [
  "F841", # unused variable
  "E501" # Line to long
]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.flake8-bandit]
check-typed-exception = true
```
